version: '2'
services:
  influxdb:
    image: influxdb:latest
    ports:
      - '8086:8086'
    volumes:
      - influxdb-storage:/mnt/shared/code/influxdb2
    environment:
      - INFLUXDB_DB-db0
      - INFLUX_ADMIN_USER=ESD_python
      - INFLUXDB_ADMIN_PASSWORD-Kush2809#
  volumes:
    influxdb-storage:
